### PR TITLE
Render html formatting for general sites in assistant text results

### PR DESCRIPTION
**Pull request by twinkarma**
The assistant backend now partially extracts html formatting from general site. This PR allows the plugin to display the formatted text.

Added `text_html_mapping` field to ScrapeContent in the backend that stores the html node structures. When combined with the text, it can be used to dynamically generate formatted text and allowing react components to be inserted in the middle.

### CODE REVIEW

**Comment by rosannamilner** [comment]
Looks good and readable!

**Review by rosannamilner — APPROVED** [review]
Looks good and readable!

**Review by Sallaa — APPROVED** [review]

**Comment by Sallaa** [comment]
@twinkarma you will need to fix the conflict so that I can merge these changes

**Comment by twinkarma** [comment]
Thanks @Sallaa, the conflict should be resolved now.

**Pull request merged**
