### PR TITLE
added domain credibility to extracted urls

### PR DESCRIPTION
**Pull request by rosannamilner**
Fixed some bugs and added keyword translations

### CODE REVIEW

**Comment by twinkarma** [comment]
Was there a change of indentation? The diffs looks like you're replacing the entire files

**Comment by rosannamilner** [comment]
Edited assistantSaga.jsx to only include the change forcing `result = null` when all batches of source credibility return empty (lines 268->270)

**Review by twinkarma — APPROVED** [review]
LGTM!

**Comment by Sallaa** [comment]
Btw, the indentation part is probably coming from the pre-commit hook that adds Prettier formatting when needed for consistency over the codebase.

**Pull request merged**
