### PR TITLE
Change Text Topics to Text Entities for the asst. named entity widget

### PR DESCRIPTION
**Pull request by twinkarma**

### CODE REVIEW

**Comment by twinkarma** [comment]
@Sallaa what branch should this be merged into? deepfake-v4 or beta-master?

**Comment by Sallaa** [comment]
@twinkarma I will merge it to deepfake-v4 for now, and then will merge it to beta-master. This is because @smdlafp-dev has been developing the new translation engine with the deepfake-v4 branch

**Comment by twinkarma** [comment]
Strange. I'll just close this, rebase locally then do another pull request.

**Comment by twinkarma** [comment]
@Sallaa not sure how but looks like the change has been merged in a while ago!

**Comment by Sallaa** [comment]
Ah, great! @AFPMedialab  probably merged it with some other commits. You can close the branch if you are done with it 🙂

**Pull request closed without merging**
