### PR TITLE
Add synthetic image/deepfake tools to lists 

### PR DESCRIPTION
**Pull request by rosannamilner**
Adding Synthetic Image Detection and Deepfake Image/Video tools to Recommended Tools under Media Card and Local File Selected
- correct SVG images for all tools 
    - I struggled to do it the way you suggested Valentin, this way currently works but I'm happy to change/improve it
- added the new actions in AssistantRulebook.jsx
- added check when loading tools for beta_tester
- on selecting the tool, the image/video uri is added to URL and tool is automatically run
    - currently receiving 400 for the requests

Corresponding InVID-Translations PR: https://github.com/AFP-Medialab/InVID-Translations/pull/100

### CODE REVIEW

**Comment by Sallaa** [comment]
- I have fixed the icons import for the PR. I have set the size to 24px, but feel free to make it bigger if you want. We use 24px elsewhere in the plugin.

- Could you look into the permissions needed to display some of the tools and restrict the display if the user does not have sufficient permissions? For example, the Synthetic Image Detection needs the beta tester role. I also invite you to directly grab the rolesNeeded array for the tools in `Tools.jsx` similarly to how I imported the icons, to make sure that the user can display the tools.

- Last thing is: I saw you replaced the `url` const in the tools to take the URL params instead. I think this will introduce a regression where we will lose some of the redux store information. You can test this by going to a tool (e.g. synthetic image detection), use a local image, then submit for analysis, then go to another tool and come back to the first tool. The results and the image chosen are normally kept in the redux store. So a better way to handle the URL params would be to change the redux store in a useEffect() instead of changing the `url` const.

**Comment by rosannamilner** [comment]
> * I have fixed the icons import for the PR. I have set the size to 24px, but feel free to make it bigger if you want. We use 24px elsewhere in the plugin so you can also keep this size to keep it consistent with the other pages.

Thanks! This makes sense now.

> * Could you look into the permissions needed to display some of the tools and restrict the display if the user does not have sufficient permissions? For example, the Synthetic Image Detection needs the beta tester role. I also invite you to directly grab the rolesNeeded array for the tools in `Tools.jsx` similarly to how I imported the icons, to make sure that the user can display the tools.

This should be done and it works for me, please let me know if you spot any problems.

> * Last thing is: I saw you replaced the `url` const in the tools to take the URL params instead. I think this will introduce a regression where we will lose some of the redux store information. You can test this by going to a tool (e.g. synthetic image detection), use a local image, then submit for analysis, then go to another tool and come back to the first tool. The results and the image chosen are normally kept in the redux store. So a better way to handle the URL params would be to change the redux store in a useEffect() instead of changing the `url` const.

I've added setDeepfakeUrlImage (and corresponding for other two tools) in the actions and reducer. I then set the correct URL (the resultUrl of the media selected) in the AssistantProcessUrlActions::handleClick. However this is not done in a useEffect() as you suggested, and I'm not sure how to. The value of state.deepfakeImage.url is "" on handleClick unless I set in it the Assistant.

**Comment by Sallaa** [comment]
Hi @rosannamilner can you review the changes I made to your PR ? If everything is good on your end, I will merge it.

- I removed sending the url. I think it'll make the code easier. Sorry for leading you this way. So instead everything is sent through Redux and a useEffect auto-submits the form if applicable.
- I fixed an infinite loop that was occurring with the new useEffect
- I also added some small refactoring for the roles.

**Comment by rosannamilner** [comment]
> Hi @rosannamilner can you review the changes I made to your PR ? If everything is good on your end, I will merge it.
> 
> * I removed sending the url. I think it'll make the code easier. Sorry for leading you this way. So instead everything is sent through Redux and a useEffect auto-submits the form if applicable.
> * I fixed an infinite loop that was occurring with the new useEffect
> * I also added some small refactoring for the roles.

Thanks a lot - it looks good and makes more sense doing it this way. Happy for it to be merged

**Review by Sallaa — APPROVED** [review]

**Pull request merged**
