### PR TITLE
Adds a visual cue between images and videos

### PR DESCRIPTION
**Pull request by jmafoster1**
- I have added "Images" and "Videos" titles to the "Extracted media files" card.
image
- I have also moved "Select the media you would like to verify" as a subtitle rather than content within the card to make it more visually pleasing
- I am filtering out single pixel tracking pngs as there's nothing to inspect here and it might confuse people (Question: Should we warn users when this occurs, or would it confuse them?)
- I have added a light checkerboard background to make "white on transparent" PNG images visible, e.g. 
image

I am new to both this project and react, so any feedback on any of this would be much appreciated.

### CODE REVIEW

**Review by rosannamilner — APPROVED** [review]
Looks good, I will leave Valentin to comment on the UI. The checkered background and filtered image list improves the Media card a lot!

**Comment by jmafoster1** [comment]
Thanks @Sallaa for your useful feedback. I'll sort those out and update the PR.
For pages with images and videos, I asked the exact same question! I've been testing it with this link: https://www.bbc.co.uk/news/av/world-europe-54923014
Please let me know if you find any other pages that work like this

**Comment by Sallaa** [comment]
Great @jmafoster1 I am able to reproduce the state with your link. Another thing I forgot to mention, which could improve the UX a little bit: making the cursor change to pointer when hovering media to inform the user that this is clickable content (this is also needed for the video link).

**Comment by jmafoster1** [comment]
I've switched to using an accordion view for images and videos. I'm not sure whether I like it or not. See what you think.

**Review by Sallaa — APPROVED** [review]
To me this looks good, I think it'd be useful to get some end-user feedback on the accordion.

I know that some end users like the UI to be "screenshot-friendly" and having the two sections collapsed could help for when they conduct trainings. They could show an image selected and show that there are two media sections in the same screenshot.

I will go ahead and merge this for now. We can change the UI once we collect more feedback.

**Pull request merged**
